### ISSUE TITLE
Can't define attribute of type BOOL

### ISSUE THREAD

**Issue by aleksanderhayes** [serverless-components/aws-dynamodb#23]
```yml
inputs:
  name: ${name}-${stage}
  attributeDefinitions:
    - AttributeName: mobileNumber
      AttributeType: S
    - AttributeName: orderId
      AttributeType: S
    - AttributeName: isSettle
      AttributeType: BOOL
```

1 validation error detected: Value 'BOOL' at 'attributeDefinitions.3.member.attributeType' failed to satisfy constraint: Member must satisfy enum value set: [B, N, S]
