### ISSUE TITLE
Global Secondary Index Support

### ISSUE THREAD

**Issue by barrysteyn** [serverless-components/aws-dynamodb#7]
Global secondary indexes seems is very important. Here is an idea how it could be supported:

```
myTable:
  component: '@serverless/aws-dynamodb'
  inputs:
    name: nameOfTable # optional
    attributeDefinitions:
      - AttributeName: id
        AttributeType: S
    keySchema:
      - AttributeName: id
        KeyType: HASH
    region: us-east-1
    globalSecondaryIndexes:
      - IndexName: nameOfGSIndex
      - KeySchema:
         - AttributeName: id
            KeyType: HASH
```
